version: '3.8'
services:
  base_datos:
    image: mysql:8.0
    container_name: mysql_clase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_clase
      MYSQL_DATABASE: control_estudios # Crea directamente la BD del proyecto 
    
    ports:
      - "3307:3306" # Redirección defensiva para evitar conflictos
    
    volumes: 
        # Mapea el disco virtual del contenedor a una carpeta local
      - ./mysql_data:/var/lib/mysql

        # Script inicial de creación que se autoejecuta al encender por primera vez
      - ./sql/creacion_estructura.sql:/docker-entrypoint-initdb.d/init.sql